version: '3.8'

services:

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: shop-backend
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://195.2.70.19:3306/shop_db?useSSL=false&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: nnelkane
      SPRING_DATASOURCE_PASSWORD: 20114545
    restart: on-failure

  frontend:
    build:
      context: ./shop-ui
      dockerfile: Dockerfile
    container_name: shop-frontend
    ports:
      - "3000:80"
    depends_on:
      - backend

volumes:
  mysql-data:
    driver: local