version: '3.8'

services:
  mysql:
    image: mysql:8
    container_name: shop-mysql
    environment:
      MYSQL_ROOT_PASSWORD: ""
      MYSQL_DATABASE: shop_db
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 5s
      retries: 10

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: shop-backend
    depends_on:
      mysql:
        condition: service_healthy
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/shop_db?useSSL=false&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 
    restart: on-failure

  frontend:
    build:
      context: ./shop-ui
      dockerfile: Dockerfile
    container_name: shop-frontend
    ports:
      - "3000:80"
    depends_on:
      - backend

volumes:
  mysql-data:
    driver: local